# Generated by Django 4.2.7 on 2026-01-07 11:53

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FirewallRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the firewall rule', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Description of what this rule does', null=True)),
                ('rule_type', models.CharField(choices=[('allow', 'Allow'), ('block', 'Block'), ('rate_limit', 'Rate Limit')], help_text='Type of firewall rule', max_length=20)),
                ('ip_range', models.CharField(help_text='IP range (CIDR notation) or single IP', max_length=100)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Whether this rule is currently enforced')),
                ('priority', models.IntegerField(default=0, help_text='Rules with higher priority are evaluated first')),
                ('rate_limit_requests', models.IntegerField(blank=True, help_text='For rate_limit rules: max requests allowed', null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('rate_limit_window_seconds', models.IntegerField(blank=True, help_text='For rate_limit rules: time window in seconds', null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this rule was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last time this rule was modified')),
            ],
            options={
                'verbose_name': 'Firewall Rule',
                'verbose_name_plural': 'Firewall Rules',
                'ordering': ['-priority', 'name'],
            },
        ),
        migrations.CreateModel(
            name='FirewallStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, db_index=True, help_text='Date of the statistics', unique=True)),
                ('total_requests', models.IntegerField(default=0, help_text='Total access attempts on this date', validators=[django.core.validators.MinValueValidator(0)])),
                ('allowed_requests', models.IntegerField(default=0, help_text='Allowed access attempts', validators=[django.core.validators.MinValueValidator(0)])),
                ('blocked_requests', models.IntegerField(default=0, help_text='Blocked access attempts', validators=[django.core.validators.MinValueValidator(0)])),
                ('invalid_requests', models.IntegerField(default=0, help_text='Invalid IP format attempts', validators=[django.core.validators.MinValueValidator(0)])),
                ('unique_ips', models.IntegerField(default=0, help_text='Number of unique IP addresses', validators=[django.core.validators.MinValueValidator(0)])),
                ('avg_response_time_ms', models.FloatField(blank=True, help_text='Average verification response time', null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('last_updated', models.DateTimeField(auto_now=True, help_text='Last time statistics were updated')),
            ],
            options={
                'verbose_name': 'Firewall Statistics',
                'verbose_name_plural': 'Firewall Statistics',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='IPWhitelist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(help_text='IPv4 address to whitelist', protocol='IPv4', unique=True)),
                ('ip_integer', models.BigIntegerField(help_text='Integer representation of IP address', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(4294967295)])),
                ('collatz_hash', models.CharField(db_index=True, help_text='SHA1-E3 hash of Collatz sequence', max_length=256, unique=True)),
                ('collatz_sequence_length', models.IntegerField(help_text='Length of Collatz sequence generated from IP', validators=[django.core.validators.MinValueValidator(1)])),
                ('collatz_steps_to_one', models.IntegerField(help_text='Number of steps to reach 1 in Collatz sequence', validators=[django.core.validators.MinValueValidator(0)])),
                ('collatz_max_value', models.BigIntegerField(help_text='Maximum value reached in Collatz sequence', validators=[django.core.validators.MinValueValidator(0)])),
                ('name', models.CharField(blank=True, help_text="Human-readable name for this IP (e.g., 'Production Server')", max_length=255, null=True)),
                ('description', models.TextField(blank=True, help_text='Description of why this IP is whitelisted', null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Whether this IP is currently allowed')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this IP was added to whitelist')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last time this entry was modified')),
                ('last_verified', models.DateTimeField(blank=True, help_text='Last time this IP successfully connected', null=True)),
                ('access_count', models.IntegerField(default=0, help_text='Number of successful access attempts', validators=[django.core.validators.MinValueValidator(0)])),
            ],
            options={
                'verbose_name': 'IP Whitelist Entry',
                'verbose_name_plural': 'IP Whitelist Entries',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['ip_address'], name='firewall_ga_ip_addr_95ab03_idx'), models.Index(fields=['collatz_hash'], name='firewall_ga_collatz_1593c6_idx'), models.Index(fields=['is_active'], name='firewall_ga_is_acti_e111d3_idx'), models.Index(fields=['created_at'], name='firewall_ga_created_1d08a5_idx')],
            },
        ),
        migrations.CreateModel(
            name='AccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(db_index=True, help_text='IP address that attempted connection', protocol='IPv4')),
                ('computed_hash', models.CharField(blank=True, help_text="Hash computed from incoming IP's Collatz sequence", max_length=256, null=True)),
                ('status', models.CharField(choices=[('allowed', 'Access Allowed'), ('blocked', 'Access Blocked'), ('invalid', 'Invalid IP Format')], db_index=True, help_text='Whether access was allowed or blocked', max_length=10)),
                ('user_agent', models.CharField(blank=True, help_text='HTTP User-Agent header', max_length=512, null=True)),
                ('request_path', models.CharField(blank=True, help_text='HTTP request path', max_length=1024, null=True)),
                ('request_method', models.CharField(blank=True, help_text='HTTP method (GET, POST, etc)', max_length=10, null=True)),
                ('error_message', models.TextField(blank=True, help_text='Error details if access was blocked', null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, help_text='When the access attempt occurred')),
                ('response_time_ms', models.IntegerField(blank=True, help_text='Time taken to verify access in milliseconds', null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('matched_whitelist', models.ForeignKey(blank=True, help_text='Whitelist entry that matched (if allowed)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='access_logs', to='firewall_gateway.ipwhitelist')),
            ],
            options={
                'verbose_name': 'Access Log',
                'verbose_name_plural': 'Access Logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['ip_address', 'timestamp'], name='firewall_ga_ip_addr_b2b94d_idx'), models.Index(fields=['status', 'timestamp'], name='firewall_ga_status_653e4c_idx'), models.Index(fields=['timestamp'], name='firewall_ga_timesta_99496c_idx')],
            },
        ),
    ]
