import os
import random
import string
from datetime import datetime
from securehash_project.storage.utils.sha1_sponge_collatz_enhanced import enhanced_sha1_signature

def avalanche_test():
    msg1 = b"OpenAI_crypto"
    # flip one bit (lowest bit) in the first byte
    msg2 = bytearray(msg1)
    msg2[0] ^= 0x01
    h1 = bytes.fromhex(enhanced_sha1_signature(msg1, show_progress=False))
    h2 = bytes.fromhex(enhanced_sha1_signature(msg2, show_progress=False))
    diff = sum(bin(x ^ y).count("1") for x, y in zip(h1, h2))
    total = len(h1) * 8
    return diff, total, diff/total

def bit_balance_test():
    randmsg = os.urandom(32)
    h = bytes.fromhex(enhanced_sha1_signature(randmsg, show_progress=False))
    bit_counts = [bin(b).count('1') for b in h]
    return min(bit_counts), max(bit_counts), sum(bit_counts)/len(bit_counts)

def block_size_test():
    sizes = [1, 16, 32, 64, 128]
    results = []
    for s in sizes:
        data = os.urandom(s)
        h = enhanced_sha1_signature(data, show_progress=False)
        results.append(f"Len: {s}, Hash: {h}")
    return results

def position_dependency_test():
    d1 = b'a'*30+b'88'
    d2 = b'b'+b'a'*29+b'88'
    h1 = enhanced_sha1_signature(d1, show_progress=False)
    h2 = enhanced_sha1_signature(d2, show_progress=False)
    return h1 != h2

def write_results():
    dt = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    with open("sep19results.md", "w") as f:
        f.write(f"# SHA1-E3 Basic Tests: {dt}\n\n")
        # Avalanche
        diff, tot, ratio = avalanche_test()
        f.write(f"**Avalanche Test:**\n\nBit Changes: {diff}/{tot} ({ratio*100:.2f}%)\n\n")
        # Bit balance
        mn, mx, avg = bit_balance_test()
        f.write(f"**Bit Balance Test:**\n\nMin per byte: {mn}, Max: {mx}, Avg: {avg:.2f}\n\n")
        # Block size
        f.write("**Block Size Test:**\n\n")
        for r in block_size_test():
            f.write(r+'\n')
        f.write('\n')
        # Position dependency
        posdep = position_dependency_test()
        f.write(f"**Position Dependency Test:**\n\nHashes Differ: {posdep}\n\n")
        f.write("_Generated by SHA1-E3 test script_\n")
    print("Results written to sep19results.md")

if __name__ == "__main__":
    write_results()
